DDCE-4144 - remove /unauthorised route from project as it is not used
hmrc/binding-tariff-trader-frontend pull request #375
Opened 2023-04-27 09:56 UTC by frikit

2023-04-27 09:57 UTC, frikit commented on conf/messages.cy
> -site.save_your_cover_letter=Cadw’r llythyr eglurhaol ar ffurf PDF
this was duplicate, look above

2023-04-27 09:59 UTC, frikit commented on app/controllers/actions/IdentifierAction.scala
> -        case _: InsufficientConfidenceLevel | _: UnsupportedAuthProvider | _: UnsupportedAffinityGroup |
you cant reach this branch from user journey perspective as we dont request that data from user so this branch cant be triggered

2023-04-28 12:03 UTC, EdCope requested changes
Optimize import in AuthActionSpec
and rename test https://github.com/hmrc/binding-tariff-trader-frontend/blob/f56cdddafb4c46c10b19d8fbc13fe4b728c20bed/test/controllers/actions/AuthActionSpec.scala#L78 I think wasn't named right before

2023-04-28 12:40 UTC, EdCope approved these changes

2023-04-28 12:47 UTC, merged