DDCE-5033 Play 3 Migration
hmrc/binding-tariff-trader-frontend pull request #391
Opened 2024-03-20 09:18 UTC by robpetterson

2024-04-03 15:48 UTC, robpetterson commented
Have kept sbt-accessibility-linter on version  0.38 as there are some issues updating CSRF in the template which is necessary and would require an additional ticket in the future.

2024-04-05 10:36 UTC, gastonracui requested changes

2024-04-05 10:36 UTC, gastonracui commented on project/AppDependencies.scala
>      "commons-codec"                % "commons-codec"               % "1.16.0",
upgrade to 1.16.1

2024-04-05 10:36 UTC, gastonracui commented on project/CodeCoverageSettings.scala
> +    coverageExcludedFiles := "<empty>;Reverse.*;.*filters.*;.*components.*;.*repositories.*;" +
you just need 

coverageExcludedFiles := "<empty>;.*components.*;.*Routes.*;",

here

2024-04-08 12:27 UTC, gastonracui requested changes

2024-04-09 10:25 UTC, gastonracui commented on project/CodeCoverageSettings.scala
> +    coverageExcludedFiles := "<empty>;Reverse.*;.*filters.*;.*components.*;.*repositories.*;" +
".*components.*;.*repositories.*;.*Routes.*",

2024-04-09 10:57 UTC, gastonracui approved these changes

2024-04-09 10:57 UTC, merged